services:
  - type: web
    name: pandasai-web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        value: ""
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    regions:
      - oregon
